title: Stimyouli Group | Public Repo
description: Engineering and infrastructure ecosystem building scalable web systems and cloud services.
theme: # We are use a custom layout instead of a remote theme
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO Metadata
twitter:
  username: stimyouli
  card: summary_large_image
logo: /social-preview.png
social:
  name: Stimyouli Group
  links:
    - https://stimyouli.com

# Site Settings
google_fonts: "https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=Inter:wght@300;400;600&display=swap"
accent_color: "#00f2ff"
background_color: "#0a0a0c"
